name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Si tu rama principal se llama 'principal', cambia 'main' por 'principal'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar en Firebase Hosting Tradicional
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: robs-delivery-express-9fd38
